// Datos de ubicaciones para países y sus subdivisiones
export const countries: { label: string; value: string }[] = [
  { label: 'México', value: 'México' },
  { label: 'Estados Unidos', value: 'Estados Unidos' },
  { label: 'Canadá', value: 'Canadá' },
  { label: 'España', value: 'España' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Chile', value: 'Chile' },
  { label: 'Perú', value: 'Perú' },
  { label: 'Brasil', value: 'Brasil' },
  { label: 'Venezuela', value: 'Venezuela' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Panamá', value: 'Panamá' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Belice', value: 'Belice' },
];

export const states: Record<string, { label: string; value: string }[]> = {
  México: [
    { label: 'Aguascalientes', value: 'Aguascalientes' },
    { label: 'Baja California', value: 'Baja California' },
    { label: 'Baja California Sur', value: 'Baja California Sur' },
    { label: 'Campeche', value: 'Campeche' },
    { label: 'Chiapas', value: 'Chiapas' },
    { label: 'Chihuahua', value: 'Chihuahua' },
    { label: 'Coahuila', value: 'Coahuila' },
    { label: 'Colima', value: 'Colima' },
    { label: 'Ciudad de México', value: 'Ciudad de México' },
    { label: 'Durango', value: 'Durango' },
    { label: 'Guanajuato', value: 'Guanajuato' },
    { label: 'Guerrero', value: 'Guerrero' },
    { label: 'Hidalgo', value: 'Hidalgo' },
    { label: 'Jalisco', value: 'Jalisco' },
    { label: 'México', value: 'México' },
    { label: 'Michoacán', value: 'Michoacán' },
    { label: 'Morelos', value: 'Morelos' },
    { label: 'Nayarit', value: 'Nayarit' },
    { label: 'Nuevo León', value: 'Nuevo León' },
    { label: 'Oaxaca', value: 'Oaxaca' },
    { label: 'Puebla', value: 'Puebla' },
    { label: 'Querétaro', value: 'Querétaro' },
    { label: 'Quintana Roo', value: 'Quintana Roo' },
    { label: 'San Luis Potosí', value: 'San Luis Potosí' },
    { label: 'Sinaloa', value: 'Sinaloa' },
    { label: 'Sonora', value: 'Sonora' },
    { label: 'Tabasco', value: 'Tabasco' },
    { label: 'Tamaulipas', value: 'Tamaulipas' },
    { label: 'Tlaxcala', value: 'Tlaxcala' },
    { label: 'Veracruz', value: 'Veracruz' },
    { label: 'Yucatán', value: 'Yucatán' },
    { label: 'Zacatecas', value: 'Zacatecas' },
  ],
  'Estados Unidos': [
    { label: 'California', value: 'California' },
    { label: 'Texas', value: 'Texas' },
    { label: 'Florida', value: 'Florida' },
    { label: 'Nueva York', value: 'Nueva York' },
    { label: 'Illinois', value: 'Illinois' },
    { label: 'Pensilvania', value: 'Pensilvania' },
    { label: 'Ohio', value: 'Ohio' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Carolina del Norte', value: 'Carolina del Norte' },
    { label: 'Michigan', value: 'Michigan' },
  ],
  Canadá: [
    { label: 'Ontario', value: 'Ontario' },
    { label: 'Quebec', value: 'Quebec' },
    { label: 'Columbia Británica', value: 'Columbia Británica' },
    { label: 'Alberta', value: 'Alberta' },
    { label: 'Manitoba', value: 'Manitoba' },
    { label: 'Saskatchewan', value: 'Saskatchewan' },
    { label: 'Nueva Escocia', value: 'Nueva Escocia' },
    { label: 'Nuevo Brunswick', value: 'Nuevo Brunswick' },
    { label: 'Isla del Príncipe Eduardo', value: 'Isla del Príncipe Eduardo' },
    { label: 'Terranova y Labrador', value: 'Terranova y Labrador' },
  ],
  España: [
    { label: 'Madrid', value: 'Madrid' },
    { label: 'Cataluña', value: 'Cataluña' },
    { label: 'Andalucía', value: 'Andalucía' },
    { label: 'Valencia', value: 'Valencia' },
    { label: 'Galicia', value: 'Galicia' },
    { label: 'Castilla y León', value: 'Castilla y León' },
    { label: 'País Vasco', value: 'País Vasco' },
    { label: 'Castilla-La Mancha', value: 'Castilla-La Mancha' },
    { label: 'Canarias', value: 'Canarias' },
    { label: 'Aragón', value: 'Aragón' },
  ],
  Argentina: [
    { label: 'Buenos Aires', value: 'Buenos Aires' },
    { label: 'Córdoba', value: 'Córdoba' },
    { label: 'Santa Fe', value: 'Santa Fe' },
    { label: 'Mendoza', value: 'Mendoza' },
    { label: 'Tucumán', value: 'Tucumán' },
    { label: 'Entre Ríos', value: 'Entre Ríos' },
    { label: 'Salta', value: 'Salta' },
    { label: 'Chaco', value: 'Chaco' },
    { label: 'Corrientes', value: 'Corrientes' },
    { label: 'Misiones', value: 'Misiones' },
  ],
  Colombia: [
    { label: 'Bogotá', value: 'Bogotá' },
    { label: 'Antioquia', value: 'Antioquia' },
    { label: 'Valle del Cauca', value: 'Valle del Cauca' },
    { label: 'Cundinamarca', value: 'Cundinamarca' },
    { label: 'Atlántico', value: 'Atlántico' },
    { label: 'Santander', value: 'Santander' },
    { label: 'Norte de Santander', value: 'Norte de Santander' },
    { label: 'Bolívar', value: 'Bolívar' },
    { label: 'Córdoba', value: 'Córdoba' },
    { label: 'Tolima', value: 'Tolima' },
  ],
  Chile: [
    { label: 'Santiago', value: 'Santiago' },
    { label: 'Valparaíso', value: 'Valparaíso' },
    { label: 'Biobío', value: 'Biobío' },
    { label: 'Maule', value: 'Maule' },
    { label: 'O\'Higgins', value: 'O\'Higgins' },
    { label: 'Coquimbo', value: 'Coquimbo' },
    { label: 'Araucanía', value: 'Araucanía' },
    { label: 'Los Lagos', value: 'Los Lagos' },
    { label: 'Tarapacá', value: 'Tarapacá' },
    { label: 'Antofagasta', value: 'Antofagasta' },
  ],
  Perú: [
    { label: 'Lima', value: 'Lima' },
    { label: 'Arequipa', value: 'Arequipa' },
    { label: 'Cusco', value: 'Cusco' },
    { label: 'La Libertad', value: 'La Libertad' },
    { label: 'Piura', value: 'Piura' },
    { label: 'Lambayeque', value: 'Lambayeque' },
    { label: 'Junín', value: 'Junín' },
    { label: 'Puno', value: 'Puno' },
    { label: 'Callao', value: 'Callao' },
    { label: 'Ica', value: 'Ica' },
  ],
  Brasil: [
    { label: 'São Paulo', value: 'São Paulo' },
    { label: 'Río de Janeiro', value: 'Río de Janeiro' },
    { label: 'Minas Gerais', value: 'Minas Gerais' },
    { label: 'Bahía', value: 'Bahía' },
    { label: 'Paraná', value: 'Paraná' },
    { label: 'Rio Grande do Sul', value: 'Rio Grande do Sul' },
    { label: 'Pernambuco', value: 'Pernambuco' },
    { label: 'Ceará', value: 'Ceará' },
    { label: 'Pará', value: 'Pará' },
    { label: 'Santa Catarina', value: 'Santa Catarina' },
  ],
  Venezuela: [
    { label: 'Caracas', value: 'Caracas' },
    { label: 'Miranda', value: 'Miranda' },
    { label: 'Zulia', value: 'Zulia' },
    { label: 'Táchira', value: 'Táchira' },
    { label: 'Anzoátegui', value: 'Anzoátegui' },
    { label: 'Bolívar', value: 'Bolívar' },
    { label: 'Carabobo', value: 'Carabobo' },
    { label: 'Lara', value: 'Lara' },
    { label: 'Sucre', value: 'Sucre' },
    { label: 'Monagas', value: 'Monagas' },
  ],
  Ecuador: [
    { label: 'Pichincha', value: 'Pichincha' },
    { label: 'Guayas', value: 'Guayas' },
    { label: 'Azuay', value: 'Azuay' },
    { label: 'Manabí', value: 'Manabí' },
    { label: 'Santo Domingo de los Tsáchilas', value: 'Santo Domingo de los Tsáchilas' },
    { label: 'El Oro', value: 'El Oro' },
    { label: 'Los Ríos', value: 'Los Ríos' },
    { label: 'Tungurahua', value: 'Tungurahua' },
    { label: 'Imbabura', value: 'Imbabura' },
    { label: 'Chimborazo', value: 'Chimborazo' },
  ],
  Uruguay: [
    { label: 'Montevideo', value: 'Montevideo' },
    { label: 'Canelones', value: 'Canelones' },
    { label: 'Maldonado', value: 'Maldonado' },
    { label: 'Salto', value: 'Salto' },
    { label: 'Paysandú', value: 'Paysandú' },
    { label: 'Río Negro', value: 'Río Negro' },
    { label: 'Tacuarembó', value: 'Tacuarembó' },
    { label: 'Cerro Largo', value: 'Cerro Largo' },
    { label: 'Rivera', value: 'Rivera' },
    { label: 'Artigas', value: 'Artigas' },
  ],
  Paraguay: [
    { label: 'Asunción', value: 'Asunción' },
    { label: 'Central', value: 'Central' },
    { label: 'Alto Paraná', value: 'Alto Paraná' },
    { label: 'Itapúa', value: 'Itapúa' },
    { label: 'Caaguazú', value: 'Caaguazú' },
    { label: 'Paraguarí', value: 'Paraguarí' },
    { label: 'Misiones', value: 'Misiones' },
    { label: 'Ñeembucú', value: 'Ñeembucú' },
    { label: 'Amambay', value: 'Amambay' },
    { label: 'Canindeyú', value: 'Canindeyú' },
  ],
  Bolivia: [
    { label: 'La Paz', value: 'La Paz' },
    { label: 'Santa Cruz', value: 'Santa Cruz' },
    { label: 'Cochabamba', value: 'Cochabamba' },
    { label: 'Potosí', value: 'Potosí' },
    { label: 'Chuquisaca', value: 'Chuquisaca' },
    { label: 'Oruro', value: 'Oruro' },
    { label: 'Tarija', value: 'Tarija' },
    { label: 'Beni', value: 'Beni' },
    { label: 'Pando', value: 'Pando' },
  ],
  Panamá: [
    { label: 'Panamá', value: 'Panamá' },
    { label: 'Colón', value: 'Colón' },
    { label: 'Chiriquí', value: 'Chiriquí' },
    { label: 'Veraguas', value: 'Veraguas' },
    { label: 'Herrera', value: 'Herrera' },
    { label: 'Los Santos', value: 'Los Santos' },
    { label: 'Coclé', value: 'Coclé' },
    { label: 'Darién', value: 'Darién' },
    { label: 'Bocas del Toro', value: 'Bocas del Toro' },
    { label: 'Guna Yala', value: 'Guna Yala' },
  ],
  'Costa Rica': [
    { label: 'San José', value: 'San José' },
    { label: 'Alajuela', value: 'Alajuela' },
    { label: 'Cartago', value: 'Cartago' },
    { label: 'Heredia', value: 'Heredia' },
    { label: 'Guanacaste', value: 'Guanacaste' },
    { label: 'Puntarenas', value: 'Puntarenas' },
    { label: 'Limón', value: 'Limón' },
  ],
  Nicaragua: [
    { label: 'Managua', value: 'Managua' },
    { label: 'León', value: 'León' },
    { label: 'Granada', value: 'Granada' },
    { label: 'Masaya', value: 'Masaya' },
    { label: 'Chinandega', value: 'Chinandega' },
    { label: 'Matagalpa', value: 'Matagalpa' },
    { label: 'Estelí', value: 'Estelí' },
    { label: 'Carazo', value: 'Carazo' },
    { label: 'Chontales', value: 'Chontales' },
    { label: 'Rivas', value: 'Rivas' },
  ],
  Honduras: [
    { label: 'Francisco Morazán', value: 'Francisco Morazán' },
    { label: 'Cortés', value: 'Cortés' },
    { label: 'Atlántida', value: 'Atlántida' },
    { label: 'Yoro', value: 'Yoro' },
    { label: 'Colón', value: 'Colón' },
    { label: 'Olancho', value: 'Olancho' },
    { label: 'Santa Bárbara', value: 'Santa Bárbara' },
    { label: 'Copán', value: 'Copán' },
    { label: 'Ocotepeque', value: 'Ocotepeque' },
    { label: 'Lempira', value: 'Lempira' },
  ],
  'El Salvador': [
    { label: 'San Salvador', value: 'San Salvador' },
    { label: 'La Libertad', value: 'La Libertad' },
    { label: 'Santa Ana', value: 'Santa Ana' },
    { label: 'Sonsonate', value: 'Sonsonate' },
    { label: 'Usulután', value: 'Usulután' },
    { label: 'San Miguel', value: 'San Miguel' },
    { label: 'Morazán', value: 'Morazán' },
    { label: 'La Unión', value: 'La Unión' },
    { label: 'Cuscatlán', value: 'Cuscatlán' },
    { label: 'Chalatenango', value: 'Chalatenango' },
  ],
  Guatemala: [
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Quetzaltenango', value: 'Quetzaltenango' },
    { label: 'Alta Verapaz', value: 'Alta Verapaz' },
    { label: 'Huehuetenango', value: 'Huehuetenango' },
    { label: 'San Marcos', value: 'San Marcos' },
    { label: 'Escuintla', value: 'Escuintla' },
    { label: 'Chimaltenango', value: 'Chimaltenango' },
    { label: 'Sacatepéquez', value: 'Sacatepéquez' },
    { label: 'Totonicapán', value: 'Totonicapán' },
    { label: 'Sololá', value: 'Sololá' },
  ],
  Belice: [
    { label: 'Belice', value: 'Belice' },
    { label: 'Cayo', value: 'Cayo' },
    { label: 'Corozal', value: 'Corozal' },
    { label: 'Orange Walk', value: 'Orange Walk' },
    { label: 'Stann Creek', value: 'Stann Creek' },
    { label: 'Toledo', value: 'Toledo' },
  ],
};

export const cities: Record<string, { label: string; value: string }[]> = {
  // México
  'Ciudad de México': [
    { label: 'Centro Histórico', value: 'Centro Histórico' },
    { label: 'Polanco', value: 'Polanco' },
    { label: 'Roma', value: 'Roma' },
    { label: 'Benito Juárez', value: 'Benito Juárez' },
    { label: 'Cuauhtémoc', value: 'Cuauhtémoc' },
    { label: 'Miguel Hidalgo', value: 'Miguel Hidalgo' },
    { label: 'Coyoacán', value: 'Coyoacán' },
    { label: 'Iztapalapa', value: 'Iztapalapa' },
    { label: 'Gustavo A. Madero', value: 'Gustavo A. Madero' },
    { label: 'Álvaro Obregón', value: 'Álvaro Obregón' },
    { label: 'Xochimilco', value: 'Xochimilco' },
    { label: 'Tláhuac', value: 'Tláhuac' },
    { label: 'Milpa Alta', value: 'Milpa Alta' },
    { label: 'La Magdalena Contreras', value: 'La Magdalena Contreras' },
    { label: 'Ajusco', value: 'Ajusco' },
    { label: 'Iztacalco', value: 'Iztacalco' },
    { label: 'Venustiano Carranza', value: 'Venustiano Carranza' },
  ],
  'Jalisco': [
    { label: 'Guadalajara', value: 'Guadalajara' },
    { label: 'Zapopan', value: 'Zapopan' },
    { label: 'Tlaquepaque', value: 'Tlaquepaque' },
    { label: 'Tonalá', value: 'Tonalá' },
    { label: 'Puerto Vallarta', value: 'Puerto Vallarta' },
    { label: 'Autlán de Navarro', value: 'Autlán de Navarro' },
    { label: 'La Barca', value: 'La Barca' },
    { label: 'Lagos de Moreno', value: 'Lagos de Moreno' },
    { label: 'El Grullo', value: 'El Grullo' },
    { label: 'Tequila', value: 'Tequila' },
    { label: 'Ajijic', value: 'Ajijic' },
    { label: 'Chapala', value: 'Chapala' },
    { label: 'Tamazula', value: 'Tamazula' },
    { label: 'Jilotlán de los Dolores', value: 'Jilotlán de los Dolores' },
    { label: 'Ocotlán', value: 'Ocotlán' },
  ],
  'México': [
    { label: 'Toluca', value: 'Toluca' },
    { label: 'Ecatepec', value: 'Ecatepec' },
    { label: 'Naucalpán', value: 'Naucalpán' },
    { label: 'Tlalnepantla', value: 'Tlalnepantla' },
    { label: 'Chimalhuacán', value: 'Chimalhuacán' },
    { label: 'Texcoco', value: 'Texcoco' },
    { label: 'Nezahualcóyotl', value: 'Nezahualcóyotl' },
    { label: 'Ixtapaluca', value: 'Ixtapaluca' },
    { label: 'Chalco', value: 'Chalco' },
    { label: 'Atizapán de Zaragoza', value: 'Atizapán de Zaragoza' },
    { label: 'Huixquilucan', value: 'Huixquilucan' },
    { label: 'Lerma', value: 'Lerma' },
    { label: 'Tenango del Valle', value: 'Tenango del Valle' },
    { label: 'Tultitlán', value: 'Tultitlán' },
    { label: 'Metepec', value: 'Metepec' },
  ],
  'Veracruz': [
    { label: 'Veracruz', value: 'Veracruz' },
    { label: 'Xalapa', value: 'Xalapa' },
    { label: 'Coatzacoalcos', value: 'Coatzacoalcos' },
    { label: 'Poza Rica', value: 'Poza Rica' },
    { label: 'Orizaba', value: 'Orizaba' },
    { label: 'Córdoba', value: 'Córdoba' },
    { label: 'Minatitlán', value: 'Minatitlán' },
    { label: 'Tuxpan', value: 'Tuxpan' },
    { label: 'Papantla', value: 'Papantla' },
    { label: 'San Andrés Tuxtla', value: 'San Andrés Tuxtla' },
    { label: 'Boca del Río', value: 'Boca del Río' },
    { label: 'Fortín', value: 'Fortín' },
    { label: 'Acayucan', value: 'Acayucan' },
    { label: 'Naranjos', value: 'Naranjos' },
  ],
  'Puebla': [
    { label: 'Puebla', value: 'Puebla' },
    { label: 'Cholula', value: 'Cholula' },
    { label: 'Tehuacán', value: 'Tehuacán' },
    { label: 'Atlixco', value: 'Atlixco' },
    { label: 'San Martín Texmelucan', value: 'San Martín Texmelucan' },
    { label: 'Ajalpan', value: 'Ajalpan' },
    { label: 'Acatlán', value: 'Acatlán' },
    { label: 'Zacatlán', value: 'Zacatlán' },
    { label: 'Huamantla', value: 'Huamantla' },
    { label: 'Chignahuapan', value: 'Chignahuapan' },
    { label: 'San Pedro Cholula', value: 'San Pedro Cholula' },
  ],
  'Baja California': [
    { label: 'Tijuana', value: 'Tijuana' },
    { label: 'Mexicali', value: 'Mexicali' },
    { label: 'Ensenada', value: 'Ensenada' },
    { label: 'Tecate', value: 'Tecate' },
    { label: 'Rosarito', value: 'Rosarito' },
    { label: 'San Quintín', value: 'San Quintín' },
    { label: 'San Felipe', value: 'San Felipe' },
    { label: 'Santo Tomás', value: 'Santo Tomás' },
  ],
  'Nuevo León': [
    { label: 'Monterrey', value: 'Monterrey' },
    { label: 'Guadalupe', value: 'Guadalupe' },
    { label: 'San Nicolás de los Garza', value: 'San Nicolás de los Garza' },
    { label: 'Apodaca', value: 'Apodaca' },
    { label: 'Santa Catarina', value: 'Santa Catarina' },
    { label: 'San Pedro Garza García', value: 'San Pedro Garza García' },
    { label: 'Saltillo', value: 'Saltillo' },
    { label: 'Galeana', value: 'Galeana' },
    { label: 'Linares', value: 'Linares' },
    { label: 'Montermorelos', value: 'Montermorelos' },
    { label: 'Cadereyta Jiménez', value: 'Cadereyta Jiménez' },
  ],
  'Chihuahua': [
    { label: 'Chihuahua', value: 'Chihuahua' },
    { label: 'Ciudad Juárez', value: 'Ciudad Juárez' },
    { label: 'Delicias', value: 'Delicias' },
    { label: 'Parral', value: 'Parral' },
    { label: 'Cuauhtémoc', value: 'Cuauhtémoc' },
    { label: 'Ojinaga', value: 'Ojinaga' },
    { label: 'Ciudad Camargo', value: 'Ciudad Camargo' },
    { label: 'Meoqui', value: 'Meoqui' },
    { label: 'Hidalgo del Parral', value: 'Hidalgo del Parral' },
  ],
  'Sonora': [
    { label: 'Hermosillo', value: 'Hermosillo' },
    { label: 'Guaymas', value: 'Guaymas' },
    { label: 'Ciudad Obregón', value: 'Ciudad Obregón' },
    { label: 'Navojoa', value: 'Navojoa' },
    { label: 'Nogales', value: 'Nogales' },
    { label: 'San Luis Río Colorado', value: 'San Luis Río Colorado' },
    { label: 'Agua Prieta', value: 'Agua Prieta' },
    { label: 'Puerto Peñasco', value: 'Puerto Peñasco' },
    { label: 'Empalme', value: 'Empalme' },
  ],
  'Sinaloa': [
    { label: 'Culiacán', value: 'Culiacán' },
    { label: 'Mazatlán', value: 'Mazatlán' },
    { label: 'Los Mochis', value: 'Los Mochis' },
    { label: 'Guasave', value: 'Guasave' },
    { label: 'Ahome', value: 'Ahome' },
    { label: 'El Fuerte', value: 'El Fuerte' },
    { label: 'Navolato', value: 'Navolato' },
    { label: 'Cosalá', value: 'Cosalá' },
  ],
  'Guanajuato': [
    { label: 'Guanajuato', value: 'Guanajuato' },
    { label: 'León', value: 'León' },
    { label: 'Irapuato', value: 'Irapuato' },
    { label: 'Celaya', value: 'Celaya' },
    { label: 'Salamanca', value: 'Salamanca' },
    { label: 'Cortazar', value: 'Cortazar' },
    { label: 'Acambaro', value: 'Acambaro' },
    { label: 'Pénjamo', value: 'Pénjamo' },
    { label: 'Dolores Hidalgo', value: 'Dolores Hidalgo' },
    { label: 'San Miguel de Allende', value: 'San Miguel de Allende' },
  ],
  'Querétaro': [
    { label: 'Querétaro', value: 'Querétaro' },
    { label: 'San Juan del Río', value: 'San Juan del Río' },
    { label: 'Tequisquiapan', value: 'Tequisquiapan' },
    { label: 'Cadereyta', value: 'Cadereyta' },
    { label: 'Corregidora', value: 'Corregidora' },
    { label: 'El Marqués', value: 'El Marqués' },
  ],
  'Yucatán': [
    { label: 'Mérida', value: 'Mérida' },
    { label: 'Cancún', value: 'Cancún' },
    { label: 'Progreso', value: 'Progreso' },
    { label: 'Chichén Itzá', value: 'Chichén Itzá' },
    { label: 'Tizimín', value: 'Tizimín' },
    { label: 'Motul', value: 'Motul' },
    { label: 'Umán', value: 'Umán' },
    { label: 'Izamal', value: 'Izamal' },
  ],
  'Quintana Roo': [
    { label: 'Cancún', value: 'Cancún' },
    { label: 'Playa del Carmen', value: 'Playa del Carmen' },
    { label: 'Tulum', value: 'Tulum' },
    { label: 'Chetumal', value: 'Chetumal' },
    { label: 'Cozumel', value: 'Cozumel' },
    { label: 'Felipe Carrillo Puerto', value: 'Felipe Carrillo Puerto' },
    { label: 'Isla Mujeres', value: 'Isla Mujeres' },
    { label: 'Puerto Morelos', value: 'Puerto Morelos' },
  ],
  'Oaxaca': [
    { label: 'Oaxaca', value: 'Oaxaca' },
    { label: 'Puerto Escondido', value: 'Puerto Escondido' },
    { label: 'Huatulco', value: 'Huatulco' },
    { label: 'Tlacolula', value: 'Tlacolula' },
    { label: 'Ocotlán', value: 'Ocotlán' },
    { label: 'Iguala', value: 'Iguala' },
    { label: 'Juchitán', value: 'Juchitán' },
    { label: 'Etla', value: 'Etla' },
    { label: 'Coixtlahuaca', value: 'Coixtlahuaca' },
  ],
  'Guerrero': [
    { label: 'Acapulco', value: 'Acapulco' },
    { label: 'Zihuatanejo', value: 'Zihuatanejo' },
    { label: 'Chilpancingo', value: 'Chilpancingo' },
    { label: 'Iguala', value: 'Iguala' },
    { label: 'Taxco', value: 'Taxco' },
    { label: 'Tlapa', value: 'Tlapa' },
    { label: 'Juchitán', value: 'Juchitán' },
  ],
  'Michoacán': [
    { label: 'Morelia', value: 'Morelia' },
    { label: 'Uruapan', value: 'Uruapan' },
    { label: 'Lázaro Cárdenas', value: 'Lázaro Cárdenas' },
    { label: 'Zamora', value: 'Zamora' },
    { label: 'Pátzcuaro', value: 'Pátzcuaro' },
    { label: 'Apatzingán', value: 'Apatzingán' },
    { label: 'Sahuayo', value: 'Sahuayo' },
    { label: 'Zitácuaro', value: 'Zitácuaro' },
  ],
  'Hidalgo': [
    { label: 'Pachuca', value: 'Pachuca' },
    { label: 'Tulancingo', value: 'Tulancingo' },
    { label: 'Tula de Allende', value: 'Tula de Allende' },
    { label: 'Huejutla', value: 'Huejutla' },
    { label: 'Ixmiquilpan', value: 'Ixmiquilpan' },
    { label: 'Apam', value: 'Apam' },
  ],
  'Morelos': [
    { label: 'Cuernavaca', value: 'Cuernavaca' },
    { label: 'Jiutepec', value: 'Jiutepec' },
    { label: 'Cuautla', value: 'Cuautla' },
    { label: 'Jojutla', value: 'Jojutla' },
    { label: 'Yautepec', value: 'Yautepec' },
    { label: 'Tepoztlán', value: 'Tepoztlán' },
  ],
  'Tlaxcala': [
    { label: 'Tlaxcala', value: 'Tlaxcala' },
    { label: 'Apizaco', value: 'Apizaco' },
    { label: 'Huamantla', value: 'Huamantla' },
    { label: 'Zacatlán', value: 'Zacatlán' },
    { label: 'Panotla', value: 'Panotla' },
  ],
  'Aguascalientes': [
    { label: 'Aguascalientes', value: 'Aguascalientes' },
    { label: 'Calvillo', value: 'Calvillo' },
    { label: 'Jesús María', value: 'Jesús María' },
    { label: 'San Francisco de los Romo', value: 'San Francisco de los Romo' },
    { label: 'Rincón de Romos', value: 'Rincón de Romos' },
  ],
  'Baja California Sur': [
    { label: 'La Paz', value: 'La Paz' },
    { label: 'Los Cabos', value: 'Los Cabos' },
    { label: 'Ciudad Constitución', value: 'Ciudad Constitución' },
    { label: 'Cabo San Lucas', value: 'Cabo San Lucas' },
    { label: 'San José del Cabo', value: 'San José del Cabo' },
  ],
  'Campeche': [
    { label: 'Campeche', value: 'Campeche' },
    { label: 'Ciudad del Carmen', value: 'Ciudad del Carmen' },
    { label: 'Escárcega', value: 'Escárcega' },
    { label: 'Champotón', value: 'Champotón' },
    { label: 'Hecelchakán', value: 'Hecelchakán' },
  ],
  'Chiapas': [
    { label: 'Tuxtla Gutiérrez', value: 'Tuxtla Gutiérrez' },
    { label: 'San Cristóbal de las Casas', value: 'San Cristóbal de las Casas' },
    { label: 'Tapachula', value: 'Tapachula' },
    { label: 'Comitán', value: 'Comitán' },
    { label: 'Ocosingo', value: 'Ocosingo' },
    { label: 'Palenque', value: 'Palenque' },
    { label: 'Villahermosa', value: 'Villahermosa' },
  ],
  'Coahuila': [
    { label: 'Saltillo', value: 'Saltillo' },
    { label: 'Torreón', value: 'Torreón' },
    { label: 'Monclova', value: 'Monclova' },
    { label: 'Piedras Negras', value: 'Piedras Negras' },
    { label: 'Arteaga', value: 'Arteaga' },
    { label: 'Sabinas', value: 'Sabinas' },
    { label: 'Múzquiz', value: 'Múzquiz' },
  ],
  'Colima': [
    { label: 'Colima', value: 'Colima' },
    { label: 'Manzanillo', value: 'Manzanillo' },
    { label: 'Tecomán', value: 'Tecomán' },
    { label: 'Cómala', value: 'Cómala' },
  ],
  'Durango': [
    { label: 'Durango', value: 'Durango' },
    { label: 'Gómez Palacio', value: 'Gómez Palacio' },
    { label: 'Lerdo', value: 'Lerdo' },
    { label: 'Ciudad Lerdo', value: 'Ciudad Lerdo' },
    { label: 'Pueblo Nuevo', value: 'Pueblo Nuevo' },
    { label: 'El Salto', value: 'El Salto' },
  ],
  'Nayarit': [
    { label: 'Tepic', value: 'Tepic' },
    { label: 'Bahía de Banderas', value: 'Bahía de Banderas' },
    { label: 'Xalisco', value: 'Xalisco' },
    { label: 'San Blas', value: 'San Blas' },
    { label: 'Sayulita', value: 'Sayulita' },
  ],
  'San Luis Potosí': [
    { label: 'San Luis Potosí', value: 'San Luis Potosí' },
    { label: 'Ciudad Valles', value: 'Ciudad Valles' },
    { label: 'Matehuala', value: 'Matehuala' },
    { label: 'Rioverde', value: 'Rioverde' },
    { label: 'Tamazunchale', value: 'Tamazunchale' },
  ],
  'Tabasco': [
    { label: 'Villahermosa', value: 'Villahermosa' },
    { label: 'Cardenas', value: 'Cardenas' },
    { label: 'Comalcalco', value: 'Comalcalco' },
    { label: 'Cárdenas', value: 'Cárdenas' },
    { label: 'Macuspana', value: 'Macuspana' },
  ],
  'Tamaulipas': [
    { label: 'Ciudad Victoria', value: 'Ciudad Victoria' },
    { label: 'Matamoros', value: 'Matamoros' },
    { label: 'Nuevo Laredo', value: 'Nuevo Laredo' },
    { label: 'Reynosa', value: 'Reynosa' },
    { label: 'Tampico', value: 'Tampico' },
    { label: 'Ciudad Madero', value: 'Ciudad Madero' },
    { label: 'Altamira', value: 'Altamira' },
  ],
  'Zacatecas': [
    { label: 'Zacatecas', value: 'Zacatecas' },
    { label: 'Fresnillo', value: 'Fresnillo' },
    { label: 'Jerez', value: 'Jerez' },
    { label: 'Sombrerete', value: 'Sombrerete' },
    { label: 'Valparaíso', value: 'Valparaíso' },
  ],
  // Estados Unidos
  California: [
    { label: 'Los Ángeles', value: 'Los Ángeles' },
    { label: 'San Francisco', value: 'San Francisco' },
    { label: 'San Diego', value: 'San Diego' },
    { label: 'Sacramento', value: 'Sacramento' },
    { label: 'Oakland', value: 'Oakland' },
  ],
  'Texas': [
    { label: 'Houston', value: 'Houston' },
    { label: 'Dallas', value: 'Dallas' },
    { label: 'Austin', value: 'Austin' },
    { label: 'San Antonio', value: 'San Antonio' },
    { label: 'Fort Worth', value: 'Fort Worth' },
  ],
  'Florida': [
    { label: 'Miami', value: 'Miami' },
    { label: 'Orlando', value: 'Orlando' },
    { label: 'Tampa', value: 'Tampa' },
    { label: 'Jacksonville', value: 'Jacksonville' },
  ],
  'Nueva York': [
    { label: 'Nueva York', value: 'Nueva York' },
    { label: 'Buffalo', value: 'Buffalo' },
    { label: 'Rochester', value: 'Rochester' },
  ],
  Illinois: [
    { label: 'Chicago', value: 'Chicago' },
    { label: 'Springfield', value: 'Springfield' },
  ],
  'Pensilvania': [
    { label: 'Filadelfia', value: 'Filadelfia' },
    { label: 'Pittsburgh', value: 'Pittsburgh' },
  ],
  'Ohio': [
    { label: 'Columbus', value: 'Columbus' },
    { label: 'Cleveland', value: 'Cleveland' },
    { label: 'Cincinnati', value: 'Cincinnati' },
  ],
  'Georgia': [
    { label: 'Atlanta', value: 'Atlanta' },
    { label: 'Savannah', value: 'Savannah' },
  ],
  'Carolina del Norte': [
    { label: 'Charlotte', value: 'Charlotte' },
    { label: 'Raleigh', value: 'Raleigh' },
  ],
  Michigan: [
    { label: 'Detroit', value: 'Detroit' },
    { label: 'Grand Rapids', value: 'Grand Rapids' },
  ],
  // Canadá
  Ontario: [
    { label: 'Toronto', value: 'Toronto' },
    { label: 'Ottawa', value: 'Ottawa' },
    { label: 'Hamilton', value: 'Hamilton' },
  ],
  'Quebec': [
    { label: 'Montreal', value: 'Montreal' },
    { label: 'Quebec City', value: 'Quebec City' },
    { label: 'Gatineau', value: 'Gatineau' },
  ],
  'Columbia Británica': [
    { label: 'Vancouver', value: 'Vancouver' },
    { label: 'Victoria', value: 'Victoria' },
    { label: 'Surrey', value: 'Surrey' },
  ],
  Alberta: [
    { label: 'Calgary', value: 'Calgary' },
    { label: 'Edmonton', value: 'Edmonton' },
  ],
  // España
  Madrid: [
    { label: 'Madrid Centro', value: 'Madrid Centro' },
    { label: 'Chamartín', value: 'Chamartín' },
    { label: 'Retiro', value: 'Retiro' },
    { label: 'Salamanca', value: 'Salamanca' },
  ],
  'Cataluña': [
    { label: 'Barcelona', value: 'Barcelona' },
    { label: 'Girona', value: 'Girona' },
    { label: 'Tarragona', value: 'Tarragona' },
    { label: 'Lleida', value: 'Lleida' },
  ],
  'Andalucía': [
    { label: 'Sevilla', value: 'Sevilla' },
    { label: 'Málaga', value: 'Málaga' },
    { label: 'Granada', value: 'Granada' },
    { label: 'Córdoba', value: 'Córdoba' },
  ],
  'Valencia': [
    { label: 'Valencia', value: 'Valencia' },
    { label: 'Castellón', value: 'Castellón' },
    { label: 'Alicante', value: 'Alicante' },
  ],
  // Argentina
  'Buenos Aires': [
    { label: 'Buenos Aires Centro', value: 'Buenos Aires Centro' },
    { label: 'Palermo', value: 'Palermo' },
    { label: 'Recoleta', value: 'Recoleta' },
    { label: 'San Telmo', value: 'San Telmo' },
  ],
  Córdoba: [
    { label: 'Córdoba Capital', value: 'Córdoba Capital' },
    { label: 'Villa Carlos Paz', value: 'Villa Carlos Paz' },
    { label: 'Cosquín', value: 'Cosquín' },
  ],
  'Santa Fe': [
    { label: 'Rosario', value: 'Rosario' },
    { label: 'Santa Fe', value: 'Santa Fe' },
  ],
  // Colombia
  Bogotá: [
    { label: 'Centro', value: 'Centro' },
    { label: 'Chapinero', value: 'Chapinero' },
    { label: 'Usaquén', value: 'Usaquén' },
    { label: 'Suba', value: 'Suba' },
  ],
  'Antioquia': [
    { label: 'Medellín', value: 'Medellín' },
    { label: 'Envigado', value: 'Envigado' },
    { label: 'Sabaneta', value: 'Sabaneta' },
  ],
  'Valle del Cauca': [
    { label: 'Cali', value: 'Cali' },
    { label: 'Palmira', value: 'Palmira' },
  ],
  // Chile
  Santiago: [
    { label: 'Santiago Centro', value: 'Santiago Centro' },
    { label: 'Providencia', value: 'Providencia' },
    { label: 'Ñuñoa', value: 'Ñuñoa' },
    { label: 'Maipú', value: 'Maipú' },
  ],
  'Valparaíso': [
    { label: 'Valparaíso', value: 'Valparaíso' },
    { label: 'Viña del Mar', value: 'Viña del Mar' },
  ],
  // Perú
  Lima: [
    { label: 'Lima Centro', value: 'Lima Centro' },
    { label: 'Miraflores', value: 'Miraflores' },
    { label: 'San Isidro', value: 'San Isidro' },
    { label: 'Barranco', value: 'Barranco' },
  ],
  'Arequipa': [
    { label: 'Arequipa', value: 'Arequipa' },
    { label: 'Puno', value: 'Puno' },
  ],
  // Brasil
  'São Paulo': [
    { label: 'São Paulo Centro', value: 'São Paulo Centro' },
    { label: 'Vila Mariana', value: 'Vila Mariana' },
    { label: 'Pinheiros', value: 'Pinheiros' },
  ],
  'Río de Janeiro': [
    { label: 'Rio de Janeiro Centro', value: 'Rio de Janeiro Centro' },
    { label: 'Copacabana', value: 'Copacabana' },
    { label: 'Ipanema', value: 'Ipanema' },
  ],
  // Agregar ciudades para otros estados según sea necesario
};